<?php

namespace ContainerIR450Fh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNacionalidadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.e002Eqh.App\Entity\Nacionalidad' shared service.
     *
     * @return \App\Entity\Nacionalidad
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.e002Eqh": it references class "App\\Entity\\Nacionalidad" but no such service exists.');
    }
}
