<?php

namespace ContainerXEZsVub;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZJdkkZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._ZJdkkZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._ZJdkkZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AccionesExtranetController::blanquearPassword' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\NacionalidadController::delete' => ['privates', '.service_locator.e002Eqh', 'get_ServiceLocator_E002EqhService', true],
            'App\\Controller\\NacionalidadController::edit' => ['privates', '.service_locator.e002Eqh', 'get_ServiceLocator_E002EqhService', true],
            'App\\Controller\\NacionalidadController::index' => ['privates', '.service_locator.rPjkq00', 'get_ServiceLocator_RPjkq00Service', true],
            'App\\Controller\\NacionalidadController::show' => ['privates', '.service_locator.e002Eqh', 'get_ServiceLocator_E002EqhService', true],
            'App\\Controller\\OAuthController::index' => ['privates', '.service_locator.B13LZRJ', 'get_ServiceLocator_B13LZRJService', true],
            'App\\Controller\\OAuthController::logout' => ['privates', '.service_locator.M9PMcRV', 'get_ServiceLocator_M9PMcRVService', true],
            'App\\Controller\\SexoController::delete' => ['privates', '.service_locator.9Y9Jrna', 'get_ServiceLocator_9Y9JrnaService', true],
            'App\\Controller\\SexoController::edit' => ['privates', '.service_locator.9Y9Jrna', 'get_ServiceLocator_9Y9JrnaService', true],
            'App\\Controller\\SexoController::index' => ['privates', '.service_locator.2KSTP7w', 'get_ServiceLocator_2KSTP7wService', true],
            'App\\Controller\\SexoController::show' => ['privates', '.service_locator.9Y9Jrna', 'get_ServiceLocator_9Y9JrnaService', true],
            'App\\Controller\\SolicitudController::aceptarSolicitud' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\SolicitudController::nuevaSolicitud' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AccionesExtranetController:blanquearPassword' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\NacionalidadController:delete' => ['privates', '.service_locator.e002Eqh', 'get_ServiceLocator_E002EqhService', true],
            'App\\Controller\\NacionalidadController:edit' => ['privates', '.service_locator.e002Eqh', 'get_ServiceLocator_E002EqhService', true],
            'App\\Controller\\NacionalidadController:index' => ['privates', '.service_locator.rPjkq00', 'get_ServiceLocator_RPjkq00Service', true],
            'App\\Controller\\NacionalidadController:show' => ['privates', '.service_locator.e002Eqh', 'get_ServiceLocator_E002EqhService', true],
            'App\\Controller\\OAuthController:index' => ['privates', '.service_locator.B13LZRJ', 'get_ServiceLocator_B13LZRJService', true],
            'App\\Controller\\OAuthController:logout' => ['privates', '.service_locator.M9PMcRV', 'get_ServiceLocator_M9PMcRVService', true],
            'App\\Controller\\SexoController:delete' => ['privates', '.service_locator.9Y9Jrna', 'get_ServiceLocator_9Y9JrnaService', true],
            'App\\Controller\\SexoController:edit' => ['privates', '.service_locator.9Y9Jrna', 'get_ServiceLocator_9Y9JrnaService', true],
            'App\\Controller\\SexoController:index' => ['privates', '.service_locator.2KSTP7w', 'get_ServiceLocator_2KSTP7wService', true],
            'App\\Controller\\SexoController:show' => ['privates', '.service_locator.9Y9Jrna', 'get_ServiceLocator_9Y9JrnaService', true],
            'App\\Controller\\SolicitudController:aceptarSolicitud' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\SolicitudController:nuevaSolicitud' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AccionesExtranetController::blanquearPassword' => '?',
            'App\\Controller\\NacionalidadController::delete' => '?',
            'App\\Controller\\NacionalidadController::edit' => '?',
            'App\\Controller\\NacionalidadController::index' => '?',
            'App\\Controller\\NacionalidadController::show' => '?',
            'App\\Controller\\OAuthController::index' => '?',
            'App\\Controller\\OAuthController::logout' => '?',
            'App\\Controller\\SexoController::delete' => '?',
            'App\\Controller\\SexoController::edit' => '?',
            'App\\Controller\\SexoController::index' => '?',
            'App\\Controller\\SexoController::show' => '?',
            'App\\Controller\\SolicitudController::aceptarSolicitud' => '?',
            'App\\Controller\\SolicitudController::nuevaSolicitud' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AccionesExtranetController:blanquearPassword' => '?',
            'App\\Controller\\NacionalidadController:delete' => '?',
            'App\\Controller\\NacionalidadController:edit' => '?',
            'App\\Controller\\NacionalidadController:index' => '?',
            'App\\Controller\\NacionalidadController:show' => '?',
            'App\\Controller\\OAuthController:index' => '?',
            'App\\Controller\\OAuthController:logout' => '?',
            'App\\Controller\\SexoController:delete' => '?',
            'App\\Controller\\SexoController:edit' => '?',
            'App\\Controller\\SexoController:index' => '?',
            'App\\Controller\\SexoController:show' => '?',
            'App\\Controller\\SolicitudController:aceptarSolicitud' => '?',
            'App\\Controller\\SolicitudController:nuevaSolicitud' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
