<?php

namespace ContainerXEZsVub;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2KSTP7wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2KSTP7w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2KSTP7w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sexoRepository' => ['privates', 'App\\Repository\\SexoRepository', 'getSexoRepositoryService', true],
        ], [
            'sexoRepository' => 'App\\Repository\\SexoRepository',
        ]);
    }
}
