<?php

namespace ContainerXEZsVub;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E002EqhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e002Eqh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e002Eqh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'nacionalidad' => ['privates', '.errored..service_locator.e002Eqh.App\\Entity\\Nacionalidad', NULL, 'Cannot autowire service ".service_locator.e002Eqh": it references class "App\\Entity\\Nacionalidad" but no such service exists.'],
        ], [
            'nacionalidad' => 'App\\Entity\\Nacionalidad',
        ]);
    }
}
