<?php

namespace ContainerQmJFgLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FD7XGBYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FD7XGBY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FD7XGBY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'grupoKeycloak' => ['privates', '.errored.ZxAdbrw', NULL, 'Cannot determine controller argument for "App\\Controller\\GrupoKeycloakController::show()": the $grupoKeycloak argument is type-hinted with the non-existent class or interface: "App\\Entity\\GrupoKeycloak".'],
        ], [
            'grupoKeycloak' => '?',
        ]);
    }
}
