<?php

namespace ContainerQmJFgLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EyFN_5oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EyFN.5o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EyFN.5o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'grupoKeycloakRepository' => ['privates', '.errored.RVb4V32', NULL, 'Cannot determine controller argument for "App\\Controller\\GrupoKeycloakController::index()": the $grupoKeycloakRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\GrupoKeycloakRepository".'],
        ], [
            'grupoKeycloakRepository' => '?',
        ]);
    }
}
