<?php

namespace ContainerQmJFgLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4CMWb8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4C_mWb8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4C_mWb8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'menuitemRepository' => ['privates', 'App\\Repository\\MenuitemRepository', 'getMenuitemRepositoryService', true],
        ], [
            'menuitemRepository' => 'App\\Repository\\MenuitemRepository',
        ]);
    }
}
