<?php

namespace ContainerQmJFgLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XgZJDCAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XgZJDCA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XgZJDCA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'menuitem' => ['privates', '.errored..service_locator.XgZJDCA.App\\Entity\\Menuitem', NULL, 'Cannot autowire service ".service_locator.XgZJDCA": it references class "App\\Entity\\Menuitem" but no such service exists.'],
        ], [
            'menuitem' => 'App\\Entity\\Menuitem',
        ]);
    }
}
