<?php

namespace ContainerQmJFgLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_CWG9fSiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.cWG9fSi' shared service.
     *
     * @return \App\Entity\GrupoKeycloak
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\GrupoKeycloakController::edit()": the $grupoKeycloak argument is type-hinted with the non-existent class or interface: "App\\Entity\\GrupoKeycloak".');
    }
}
