<?php

namespace ContainerQmJFgLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Alup9hMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.alup9hM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.alup9hM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rolKeycloak' => ['privates', '.errored.keUE8J5', NULL, 'Cannot determine controller argument for "App\\Controller\\RolKeycloakController::delete()": the $rolKeycloak argument is type-hinted with the non-existent class or interface: "App\\Entity\\RolKeycloak".'],
        ], [
            'rolKeycloak' => '?',
        ]);
    }
}
