<?php

namespace ContainerQmJFgLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_KeUE8J5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.keUE8J5' shared service.
     *
     * @return \App\Entity\RolKeycloak
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\RolKeycloakController::delete()": the $rolKeycloak argument is type-hinted with the non-existent class or interface: "App\\Entity\\RolKeycloak".');
    }
}
