<?php

namespace ContainerQmJFgLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9Y9JrnaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9Y9Jrna' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9Y9Jrna'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sexo' => ['privates', '.errored..service_locator.9Y9Jrna.App\\Entity\\Sexo', NULL, 'Cannot autowire service ".service_locator.9Y9Jrna": it references class "App\\Entity\\Sexo" but no such service exists.'],
        ], [
            'sexo' => 'App\\Entity\\Sexo',
        ]);
    }
}
