<?php

namespace ContainerQmJFgLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_RVb4V32Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.RVb4V32' shared service.
     *
     * @return \App\Repository\GrupoKeycloakRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\GrupoKeycloakController::index()": the $grupoKeycloakRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\GrupoKeycloakRepository".');
    }
}
