<?php

namespace ContainerQmJFgLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatosDeInicioCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DatosDeInicioCommand' shared autowired service.
     *
     * @return \App\Command\DatosDeInicioCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/DatosDeInicioCommand.php';

        $container->privates['App\\Command\\DatosDeInicioCommand'] = $instance = new \App\Command\DatosDeInicioCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('datos-de-inicio');

        return $instance;
    }
}
