<?php

namespace ContainerQmJFgLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNuevaSolicitudTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\NuevaSolicitudType' shared autowired service.
     *
     * @return \App\Form\NuevaSolicitudType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/NuevaSolicitudType.php';

        return $container->privates['App\\Form\\NuevaSolicitudType'] = new \App\Form\NuevaSolicitudType();
    }
}
