<?php

namespace ContainerQmJFgLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSimplethingsEntityaudit_ReaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'simplethings_entityaudit.reader' shared service.
     *
     * @return \SimpleThings\EntityAudit\AuditReader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/SQLResultCasing.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/entity-audit-bundle/src/AuditReader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/lib/Doctrine/Persistence/ObjectManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php';

        return $container->services['simplethings_entityaudit.reader'] = ($container->services['simplethings_entityaudit.manager'] ?? $container->load('getSimplethingsEntityaudit_ManagerService'))->createAuditReader(($container->services['doctrine'] ?? $container->getDoctrineService())->getManager('default'));
    }
}
