<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dispositivo extends \App\Entity\Dispositivo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'nicname', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'fechaAlta', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'fechaBaja', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'solicitudes', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'personaJuridica', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'usuarioDispositivos', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'tipoDispositivo', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'fechaEliminacion', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'admisiones', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'invitaciones'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'nicname', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'fechaAlta', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'fechaBaja', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'solicitudes', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'personaJuridica', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'usuarioDispositivos', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'tipoDispositivo', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'fechaEliminacion', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'admisiones', '' . "\0" . 'App\\Entity\\Dispositivo' . "\0" . 'invitaciones'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dispositivo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNicname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNicname', []);

        return parent::getNicname();
    }

    /**
     * {@inheritDoc}
     */
    public function setNicname(string $nicname): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNicname', [$nicname]);

        return parent::setNicname($nicname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta(?\DateTimeInterface $fechaAlta): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', [$fechaAlta]);

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaBaja(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaBaja', []);

        return parent::getFechaBaja();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaBaja(?\DateTimeInterface $fechaBaja): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaBaja', [$fechaBaja]);

        return parent::setFechaBaja($fechaBaja);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitudes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitudes', []);

        return parent::getSolicitudes();
    }

    /**
     * {@inheritDoc}
     */
    public function addSolicitude(\App\Entity\Solicitud $solicitude): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSolicitude', [$solicitude]);

        return parent::addSolicitude($solicitude);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSolicitude(\App\Entity\Solicitud $solicitude): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSolicitude', [$solicitude]);

        return parent::removeSolicitude($solicitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonaJuridica(): ?\App\Entity\PersonaJuridica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonaJuridica', []);

        return parent::getPersonaJuridica();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonaJuridica(?\App\Entity\PersonaJuridica $personaJuridica): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonaJuridica', [$personaJuridica]);

        return parent::setPersonaJuridica($personaJuridica);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioDispositivos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioDispositivos', []);

        return parent::getUsuarioDispositivos();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsuarioDispositivo(\App\Entity\UsuarioDispositivo $usuarioDispositivo): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsuarioDispositivo', [$usuarioDispositivo]);

        return parent::addUsuarioDispositivo($usuarioDispositivo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsuarioDispositivo(\App\Entity\UsuarioDispositivo $usuarioDispositivo): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsuarioDispositivo', [$usuarioDispositivo]);

        return parent::removeUsuarioDispositivo($usuarioDispositivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoDispositivo(): ?\App\Entity\TipoDispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoDispositivo', []);

        return parent::getTipoDispositivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDispositivo(?\App\Entity\TipoDispositivo $tipoDispositivo): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDispositivo', [$tipoDispositivo]);

        return parent::setTipoDispositivo($tipoDispositivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEliminacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEliminacion', []);

        return parent::getFechaEliminacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEliminacion(?\DateTimeInterface $fechaEliminacion): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEliminacion', [$fechaEliminacion]);

        return parent::setFechaEliminacion($fechaEliminacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmisiones(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmisiones', []);

        return parent::getAdmisiones();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdmisione(\App\Entity\Admision $admisione): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdmisione', [$admisione]);

        return parent::addAdmisione($admisione);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdmisione(\App\Entity\Admision $admisione): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdmisione', [$admisione]);

        return parent::removeAdmisione($admisione);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvitaciones(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvitaciones', []);

        return parent::getInvitaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function addInvitacione(\App\Entity\Invitacion $invitacione): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInvitacione', [$invitacione]);

        return parent::addInvitacione($invitacione);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInvitacione(\App\Entity\Invitacion $invitacione): \App\Entity\Dispositivo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInvitacione', [$invitacione]);

        return parent::removeInvitacione($invitacione);
    }

}
