<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PersonaJuridica extends \App\Entity\PersonaJuridica implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'cuit', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'razonSocial', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'fechaAlta', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'fechaBaja', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'solicitudes', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'dispositivos', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'representaciones', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'fechaEliminacion'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'cuit', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'razonSocial', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'fechaAlta', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'fechaBaja', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'solicitudes', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'dispositivos', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'representaciones', '' . "\0" . 'App\\Entity\\PersonaJuridica' . "\0" . 'fechaEliminacion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PersonaJuridica $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCuit(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuit', []);

        return parent::getCuit();
    }

    /**
     * {@inheritDoc}
     */
    public function setCuit(string $cuit): \App\Entity\PersonaJuridica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCuit', [$cuit]);

        return parent::setCuit($cuit);
    }

    /**
     * {@inheritDoc}
     */
    public function getRazonSocial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazonSocial', []);

        return parent::getRazonSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazonSocial(string $razonSocial): \App\Entity\PersonaJuridica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazonSocial', [$razonSocial]);

        return parent::setRazonSocial($razonSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta(?\DateTimeInterface $fechaAlta): \App\Entity\PersonaJuridica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', [$fechaAlta]);

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaBaja(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaBaja', []);

        return parent::getFechaBaja();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaBaja(?\DateTimeInterface $fechaBaja): \App\Entity\PersonaJuridica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaBaja', [$fechaBaja]);

        return parent::setFechaBaja($fechaBaja);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitudes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitudes', []);

        return parent::getSolicitudes();
    }

    /**
     * {@inheritDoc}
     */
    public function addSolicitude(\App\Entity\Solicitud $solicitude): \App\Entity\PersonaJuridica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSolicitude', [$solicitude]);

        return parent::addSolicitude($solicitude);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSolicitude(\App\Entity\Solicitud $solicitude): \App\Entity\PersonaJuridica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSolicitude', [$solicitude]);

        return parent::removeSolicitude($solicitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getDispositivos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDispositivos', []);

        return parent::getDispositivos();
    }

    /**
     * {@inheritDoc}
     */
    public function addDispositivo(\App\Entity\Dispositivo $dispositivo): \App\Entity\PersonaJuridica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDispositivo', [$dispositivo]);

        return parent::addDispositivo($dispositivo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDispositivo(\App\Entity\Dispositivo $dispositivo): \App\Entity\PersonaJuridica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDispositivo', [$dispositivo]);

        return parent::removeDispositivo($dispositivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepresentaciones(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepresentaciones', []);

        return parent::getRepresentaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function addRepresentacione(\App\Entity\Representacion $representacione): \App\Entity\PersonaJuridica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRepresentacione', [$representacione]);

        return parent::addRepresentacione($representacione);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRepresentacione(\App\Entity\Representacion $representacione): \App\Entity\PersonaJuridica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRepresentacione', [$representacione]);

        return parent::removeRepresentacione($representacione);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEliminacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEliminacion', []);

        return parent::getFechaEliminacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEliminacion(?\DateTimeInterface $fechaEliminacion): \App\Entity\PersonaJuridica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEliminacion', [$fechaEliminacion]);

        return parent::setFechaEliminacion($fechaEliminacion);
    }

}
