<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PersonaFisica extends \App\Entity\PersonaFisica implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'apellido', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'nombres', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'nroDoc', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'cuitCuil', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'fechaNac', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'user', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'tipoCuitCuil', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'sexo', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'estadoCivil', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'nacionalidad', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'solicitudes', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'tipoDocumento', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'representaciones', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'fechaEliminacion', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'admisiones', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'invitaciones'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'apellido', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'nombres', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'nroDoc', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'cuitCuil', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'fechaNac', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'user', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'tipoCuitCuil', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'sexo', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'estadoCivil', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'nacionalidad', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'solicitudes', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'tipoDocumento', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'representaciones', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'fechaEliminacion', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'admisiones', '' . "\0" . 'App\\Entity\\PersonaFisica' . "\0" . 'invitaciones'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PersonaFisica $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setUppers(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUppers', []);

        parent::setUppers();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', []);

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido(string $apellido): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', [$apellido]);

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombres(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombres', []);

        return parent::getNombres();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombres(string $nombres): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombres', [$nombres]);

        return parent::setNombres($nombres);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroDoc(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroDoc', []);

        return parent::getNroDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroDoc(string $nroDoc): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroDoc', [$nroDoc]);

        return parent::setNroDoc($nroDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getCuitCuil(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuitCuil', []);

        return parent::getCuitCuil();
    }

    /**
     * {@inheritDoc}
     */
    public function setCuitCuil(string $cuitCuil): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCuitCuil', [$cuitCuil]);

        return parent::setCuitCuil($cuitCuil);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNac(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNac', []);

        return parent::getFechaNac();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNac(?\DateTimeInterface $fechaNac): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNac', [$fechaNac]);

        return parent::setFechaNac($fechaNac);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoCuitCuil(): ?\App\Entity\TipoCuitCuil
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoCuitCuil', []);

        return parent::getTipoCuitCuil();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoCuitCuil(?\App\Entity\TipoCuitCuil $tipoCuitCuil): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoCuitCuil', [$tipoCuitCuil]);

        return parent::setTipoCuitCuil($tipoCuitCuil);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo(): ?\App\Entity\Sexo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo(?\App\Entity\Sexo $sexo): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', [$sexo]);

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoCivil(): ?\App\Entity\EstadoCivil
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoCivil', []);

        return parent::getEstadoCivil();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoCivil(?\App\Entity\EstadoCivil $estadoCivil): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoCivil', [$estadoCivil]);

        return parent::setEstadoCivil($estadoCivil);
    }

    /**
     * {@inheritDoc}
     */
    public function getNacionalidad(): ?\App\Entity\Nacionalidad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNacionalidad', []);

        return parent::getNacionalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setNacionalidad(?\App\Entity\Nacionalidad $nacionalidad): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNacionalidad', [$nacionalidad]);

        return parent::setNacionalidad($nacionalidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitudes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitudes', []);

        return parent::getSolicitudes();
    }

    /**
     * {@inheritDoc}
     */
    public function addSolicitude(\App\Entity\Solicitud $solicitude): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSolicitude', [$solicitude]);

        return parent::addSolicitude($solicitude);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSolicitude(\App\Entity\Solicitud $solicitude): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSolicitude', [$solicitude]);

        return parent::removeSolicitude($solicitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoDocumento(): ?\App\Entity\TipoDocumento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoDocumento', []);

        return parent::getTipoDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDocumento(?\App\Entity\TipoDocumento $tipoDocumento): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDocumento', [$tipoDocumento]);

        return parent::setTipoDocumento($tipoDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepresentaciones(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepresentaciones', []);

        return parent::getRepresentaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function addRepresentacione(\App\Entity\Representacion $representacione): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRepresentacione', [$representacione]);

        return parent::addRepresentacione($representacione);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRepresentacione(\App\Entity\Representacion $representacione): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRepresentacione', [$representacione]);

        return parent::removeRepresentacione($representacione);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEliminacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEliminacion', []);

        return parent::getFechaEliminacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEliminacion(?\DateTimeInterface $fechaEliminacion): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEliminacion', [$fechaEliminacion]);

        return parent::setFechaEliminacion($fechaEliminacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmisiones(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmisiones', []);

        return parent::getAdmisiones();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdmisione(\App\Entity\Admision $admisione): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdmisione', [$admisione]);

        return parent::addAdmisione($admisione);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdmisione(\App\Entity\Admision $admisione): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdmisione', [$admisione]);

        return parent::removeAdmisione($admisione);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvitaciones(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvitaciones', []);

        return parent::getInvitaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function addInvitacione(\App\Entity\Invitacion $invitacione): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInvitacione', [$invitacione]);

        return parent::addInvitacione($invitacione);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInvitacione(\App\Entity\Invitacion $invitacione): \App\Entity\PersonaFisica
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInvitacione', [$invitacione]);

        return parent::removeInvitacione($invitacione);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

}
