<?php

namespace ContainerW9BhmEQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YvyoM6jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yvyoM6j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yvyoM6j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rolKeycloakRepository' => ['privates', 'App\\Repository\\RolKeycloakRepository', 'getRolKeycloakRepositoryService', true],
        ], [
            'rolKeycloakRepository' => 'App\\Repository\\RolKeycloakRepository',
        ]);
    }
}
