<?php

namespace ContainerW9BhmEQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5j_GAkwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5j.GAkw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5j.GAkw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'grupoKeycloak' => ['privates', '.errored.eJ6x0It', NULL, 'Cannot determine controller argument for "App\\Controller\\GrupoKeycloakController::delete()": the $grupoKeycloak argument is type-hinted with the non-existent class or interface: "App\\Entity\\GrupoKeycloak".'],
        ], [
            'grupoKeycloak' => '?',
        ]);
    }
}
