<?php

namespace ContainerW9BhmEQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VtzUo79Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vtzUo79' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vtzUo79'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'grupo' => ['privates', '.errored..service_locator.vtzUo79.App\\Entity\\Grupo', NULL, 'Cannot autowire service ".service_locator.vtzUo79": it references class "App\\Entity\\Grupo" but no such service exists.'],
        ], [
            'grupo' => 'App\\Entity\\Grupo',
        ]);
    }
}
