<?php

namespace ContainerW9BhmEQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RPjkq00Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rPjkq00' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rPjkq00'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'nacionalidadRepository' => ['privates', 'App\\Repository\\NacionalidadRepository', 'getNacionalidadRepositoryService', true],
        ], [
            'nacionalidadRepository' => 'App\\Repository\\NacionalidadRepository',
        ]);
    }
}
