<?php

namespace ContainerW9BhmEQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGrupoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vtzUo79.App\Entity\Grupo' shared service.
     *
     * @return \App\Entity\Grupo
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vtzUo79": it references class "App\\Entity\\Grupo" but no such service exists.');
    }
}
