<?php

namespace ContainerW9BhmEQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuitemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XgZJDCA.App\Entity\Menuitem' shared service.
     *
     * @return \App\Entity\Menuitem
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.XgZJDCA": it references class "App\\Entity\\Menuitem" but no such service exists.');
    }
}
