<?php

namespace ContainerW9BhmEQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSexoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9Y9Jrna.App\Entity\Sexo' shared service.
     *
     * @return \App\Entity\Sexo
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.9Y9Jrna": it references class "App\\Entity\\Sexo" but no such service exists.');
    }
}
