<?php

namespace ContainerW9BhmEQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSimplethingsEntityaudit_LogRevisionsListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'simplethings_entityaudit.log_revisions_listener' shared service.
     *
     * @return \SimpleThings\EntityAudit\EventListener\LogRevisionsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/entity-audit-bundle/src/EventListener/LogRevisionsListener.php';

        return $container->privates['simplethings_entityaudit.log_revisions_listener'] = new \SimpleThings\EntityAudit\EventListener\LogRevisionsListener(($container->services['simplethings_entityaudit.manager'] ?? $container->load('getSimplethingsEntityaudit_ManagerService')));
    }
}
