<?php

namespace ContainerW9BhmEQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewDetailActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'SimpleThings\EntityAudit\Action\ViewDetailAction' shared service.
     *
     * @return \SimpleThings\EntityAudit\Action\ViewEntityAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/entity-audit-bundle/src/Action/ViewEntityAction.php';

        return $container->services['SimpleThings\\EntityAudit\\Action\\ViewDetailAction'] = new \SimpleThings\EntityAudit\Action\ViewEntityAction(($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['simplethings_entityaudit.reader'] ?? $container->load('getSimplethingsEntityaudit_ReaderService')));
    }
}
