<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW9BhmEQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW9BhmEQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW9BhmEQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW9BhmEQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW9BhmEQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'W9BhmEQ',
    'container.build_id' => '77fd9688',
    'container.build_time' => 1638750737,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW9BhmEQ');
