<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQmJFgLv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQmJFgLv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQmJFgLv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQmJFgLv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQmJFgLv\App_KernelDevDebugContainer([
    'container.build_hash' => 'QmJFgLv',
    'container.build_id' => '95b32e3a',
    'container.build_time' => 1638980204,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQmJFgLv');
