<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIR450Fh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIR450Fh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIR450Fh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIR450Fh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIR450Fh\App_KernelDevDebugContainer([
    'container.build_hash' => 'IR450Fh',
    'container.build_id' => 'e2bbad22',
    'container.build_time' => 1636385603,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIR450Fh');
