<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_internals_export_js-node_modules_core-js_internals_function-bind-8a1db0.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_bootstrap_dist_js_boo-91657a.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
        'validarFormularios' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_internals_export_js-node_modules_core-js_internals_function-bind-8a1db0.js',
                '/build/vendors-node_modules_core-js_modules_es_array_index-of_js-node_modules_core-js_modules_es_fun-b41eb9.js',
                '/build/validarFormularios.js',
            ],
        ],
    ],
],

]];
